### ISSUE TITLE
Fatal error if Awesome Support is not installed

### ISSUE THREAD

**Issue by kevinwhoffman** [advancedwp/awp-functionality#2]
Got this error upon activation of the awp-functionality plugin:

Fatal error: Call to undefined function wpas_add_custom_field() in .../AWP/wp-content/plugins/awp-functionality-master/lib/plugin-customizations/awesome-support/custom-fields.php on line 35

I'm guessing that fuction is defined by the AS plugin.

**Comment by kevinwhoffman** [comment]
Confirmed if Awesome Support is installed first, all is good. However, still might want to check if the function exists before making the call.

**Comment by advancedwpuser** [comment]
Fixed with 61570894d4651f1a1dfd2f3c824d66a0c7822149
